module.exports = {
    MAIN_MENU_NAME: "WALLET",
    MAIN_MENU_DESC:  "DESCRIPCION DE EL MENU WALLET",
    TOP_UP_NAME: "TOP UP",
    WITHDRAW_NAME: "WITHDRAW",
    WALLETS_NAME: "CONFIG WALLETS",
    WALLETS_DESC: "CONFIG YOUR WALLETS:",
    WALLETS_ATM: ["PAYPAL_USD" , "TRX"]
}